variables: !include plit_muon_variables.yaml
#transform: !include transform.yaml

ttbar: &ttbar
  name: ttbar
  equal_jets: False
  pattern:
    - "user.pgadow.LD_2024_05_20.410470.PhPy8EG_A14_ttbar_hdamp258p75_nonallhad.e6337_s3681_r13144_p6119_TREE/*.h5"
    - "user.pgadow.LD_2024_05_20.410471.PhPy8EG_A14_ttbar_hdamp258p75_allhad.e6337_s3681_r13144_p6119_TREE/*.h5"
    - "user.pgadow.LD_2024_05_20.601589.PhPy8EG_A14_ttbar_hdamp258p75_nonallhadron.e8547_s3797_r13144_p6119_TREE/*.h5"

global_cuts:
  train:
    - [eventNumber, "%10<=", 7]
  val:
    - [eventNumber, "%10==", 8]
  test:
    - [eventNumber, "%10==", 9]

lowpt: &lowpt
  name: lowpt
  cuts:
    - [pt, ">", 10_000]

components:
  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [muxprompt]
    num_jets: 28_000_000

  - region:
      <<: *lowpt
    sample:
      <<: *ttbar
    flavours: [npxall]
    num_jets: 7_000_000


resampling:
  target: npxall
  method: countup
  sampling_fraction: auto
  variables:
    pt:
      bins: [[10_000, 50_000, 8], [50_000, 100_000, 5], [100_000, 500_000, 20], [500_000, 1_000_000, 5]]
    eta:
      bins: [[-2.5, 2.5, 40]]

# note: sensible defaults are defined in the PreprocessingConfig constructor
global:
  jets_name: muons
  batch_size: 1_000_000
  num_jets_estimate: 5_000_000
  base_dir: /nfs/dust/atlas/user/pgadow/plit/data/preprocessed/muons_run2_35M
  ntuple_dir: /nfs/dust/atlas/user/pgadow/plit/data/ntuples
  out_dir: /nfs/dust/atlas/user/pgadow/plit/data/preprocessed/muons_run2_35M
