electrons:
  inputs:
    - pt
    - eta
    - absEta
    - phi
    - pt_track
    - eta_track
    - absEta_track
    - phi_track
    - ptvarcone30Rel
    - topoetcone30Rel
    - caloClusterSumEtRel
    - ptfrac_lepton
    - ptrel_lepton
    - dRtrackjet_lepton
    - ptfrac_track
    - ptrel_track
    - dRtrackjet_track
    - PromptLeptonImprovedInput_CandVertex_normDistToPriVtxLongitudinalBest_ThetaCutVtx
    - d0sig
    - z0sinTheta
    - SCTWeightedCharge
    - qd0
    - ntracks
    - nTracksTrackjet
    - HighPtCaloOnly
    - Loose_VarRad
    - Tight_VarRad
    - TightTrackOnly_VarRad
    - TightTrackOnly_FixedRad
  labels:
    - iffClass

electron_tracks:
  inputs:
    - pt
    - eta
    - phi
    - ptfrac
    - dr_trackjet
    - dr_lepton
    - qOverP
    - btagIp_d0
    - btagIp_z0SinTheta
    - btagIp_d0Uncertainty
    - btagIp_z0SinThetaUncertainty
    - btagIp_d0_significance
    - btagIp_z0SinTheta_significance
    - numberOfPixelHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTHits
    - numberOfSCTSharedHits
    - numberOfTRTHits
    - electron_track
  labels:
    - ftagTruthOriginLabel
    - ftagTruthTypeLabel
    - ftagTruthVertexIndex
