muons:
  inputs:
    - pt
    - eta
    - absEta
    - phi
    - pt_track
    - eta_track
    - absEta_track
    - phi_track
    - ptvarcone30TTVARel
    - topoetcone30Rel
    - caloClusterERel
    - ptfrac_lepton
    - ptrel_lepton
    - dRtrackjet_lepton
    - ptfrac_track
    - ptrel_track
    - dRtrackjet_track
    - nTracksTrackjet
    - PflowLoose_VarRad
    - PflowTight_VarRad
    - Loose_VarRad
    - Tight_VarRad
  labels:
    - iffClass
    - muonType

muon_tracks:
  inputs:
    - pt
    - eta
    - phi
    - ptfrac
    - dr_trackjet
    - dr_lepton
    - qOverP
    - btagIp_d0
    - btagIp_z0SinTheta
    - btagIp_d0Uncertainty
    - btagIp_z0SinThetaUncertainty
    - btagIp_d0_significance
    - btagIp_z0SinTheta_significance
    - numberOfPixelHits
    - numberOfInnermostPixelLayerHits
    - numberOfNextToInnermostPixelLayerHits
    - numberOfInnermostPixelLayerSharedHits
    - numberOfInnermostPixelLayerSplitHits
    - numberOfPixelSharedHits
    - numberOfPixelSplitHits
    - numberOfSCTHits
    - numberOfSCTSharedHits
    - muon_track
  labels:
    - ftagTruthOriginLabel
    - ftagTruthTypeLabel
    - ftagTruthVertexIndex
