# Xbb tagging
- name: hbb
  label: $H \rightarrow b\bar{b}$
  cuts: ["R10TruthLabel_R22v1Relabelled == 11"]
  colour: tab:blue
  category: xbb
- name: hcc
  label: $H \rightarrow c\bar{c}$
  cuts: ["R10TruthLabel_R22v1Relabelled == 12"]
  colour: "#B45F06"
  category: xbb
- name: top
  label: Inclusive Top
  cuts: ["R10TruthLabel_R22v1Relabelled in (1,6,7)"]
  colour: "#A300A3"
  category: xbb
- name: qcd
  label: QCD
  cuts: ["R10TruthLabel_R22v1Relabelled == 10"]
  colour: "#38761D"
  category: xbb
